### PR TITLE
Added RequestHeader.ContentEncoding

### PR DESCRIPTION
**Pull request by HoraceGonzalez**
Added a new `ContentEncoding` header to the `RequestHeader` DU. See here for context: https://github.com/haf/Http.fs/issues/163

One of the unfortunate consequences of this change is that the new `RequestHeader.ContentEncoding` name conflicts with the existing `ResponseHeader.ContentEncoding`. So, some people may see some compile errors after upgrading along the lines of `Expected ResponseHeader.ContentEncoding. Got RequestHeader.ContentEncoding` if the values are not fully qualified :]

### CODE REVIEW

**Comment by HoraceGonzalez** [comment]
The `Pack` target fails on my machine, too. Not sure why.

**Comment by HoraceGonzalez** [comment]
upgrading paket to 5.219.0 seems to have fixed the issue

**Comment by haf** [comment]
@HoraceGonzalez If possible, do you think you commit a `version 5.219.0` and script to use it? I've upgraded Expecto and Logary for this issue, but haven't gotten around to this repo yet, so perhaps you could do it for me?

- https://github.com/haf/expecto/blob/master/appveyor.yml
- https://github.com/logary/logary/blob/master/fake.cmd

**Comment by HoraceGonzalez** [comment]
No problemo.

**Comment by HoraceGonzalez** [comment]
@haf, I upgraded the .paket/paket.exe binary, which fixed the build. There didn't appear to be any need to update any scripts. I apologize if this isn't what you had in mind.

I think "upgrading" paket and fake to their respective CLI tool versions might be a task for another PR.

**Comment by haf** [comment]
Thank you @HoraceGonzalez

**Comment by HoraceGonzalez** [comment]
@haf, I don't suppose you'd be willing to cut a release to get this change published?

**Comment by haf** [comment]
Sure, but perhaps we can add a key to Travis to automate this?

**Comment by HoraceGonzalez** [comment]
Sure thing. I'll give it a shot!

**Pull request merged**
